language: go
go:
  - "1.11"

branches:
  only:
    Live

before_script:
  - go vet ./...
  - go get -t -v ./...
  - mkdir $GOPATH/src/server
  - cp ./* $GOPATH/src/server && cd $GOPATH/src/server
  - go build -v -o server .
  - cp $GOPATH/bin/server /
  - chmod +x server
  
script:
  - docker build -t nicocourts/server
  - echo "$DOCKER_PASSWORD" | docker login -u "nicocourts" --password-stdin
  - docker push nicocourts/server:latest